### ISSUE TITLE
Squid Games! Write The Form...

### ISSUE THREAD

**Issue by kartikgupta98** [opencodeiiita/Find-My-Roomie#129]
OPEN TO ALL (obviously)

UX writing, the language written within apps for making the interface more understandable and usable for the users. The written content within an app is as important as the visuals. User should understand all that you want to convey 🤗 and even sometimes NOT 😏 clearly understand what you want to hide by need to include because of regulations.

You must have watched squid games (if not then.... well just ask your friends about it🤦‍♂️). In the second episode the players are given a form to read and sign. The players ALREADY have a rough idea of what they are going to do, play a game and get money. But they need to informed about the other rules and the 3 clauses that exist. That is exactly what onboarding is, users have a rough idea of what the purpose of the app is, but need to be explained the specifics or other features.

You have to write a form for ONBOARDING the users for the squid games, telling them about the 3 clauses📃, the amount of money on stake 🤑and also that eliminated means that they will be killed🔪. Obviously try to make the form sound friendly, focus more on highlighting the money and the third clause and try to hide the facts about killing! But mind you all this has be done with beauty of language and not by visuals. You can play with text sizes and weights but no colours or photos. It should be black and white.

</br>  

## Submission Guideline

- The form should tell the users about the prize money, the three clauses and that eliminated means they will be killed off
- The fact that they will be killed of must sound "reasonable" in comparison to the money at stake.
- The 3 clauses should seem like the players have a free will and are not being forced to play the games
- No colours or photos to be used, though you can play with font sizes and weights.
- Submit the link to google doc in a .txt file and place the file in UX writing folder ONLY.

</br>

## Minimum Design Criteria (MDC)

Use any Shakespearean language or Yoda sentences and PR will be immediately rejected. If I (an average user) don't understand the meaning of any word, the PR will be rejected. If on reading, I feel like betting my life is not worth the money, PR will be rejected. If all the clauses are not properly explained, rejected again. Do keep all these things in mind and I hope your submission gets accepted 😊

**Comment by schandu-eng** [comment]
claim 😍great task dude

**Comment by karrocks** [comment]
You may proceed with the task😇

**Comment by anirudhhhh** [comment]
In html only??
Will the form record responses or I have to make only html of this??

**Comment by karrocks** [comment]
@anirudhhhh task has to be done in google doc
