### ISSUE TITLE
User Experience Task

### ISSUE THREAD

**Issue by karrocks** [opencodeiiita/Find-My-Roomie#2]
OPEN TO ALL. 
No need to claim this issue.
NO SUBMISSION WILL BE ACCEPTED AFTER 8th October 11:59 PM.

This first task is based on basic understanding of User Experience and User flow. 
Find my Roomie is an app that helps the user to find their ideal hostel partner, matching people who would be most compatible with each other based on various attributes (to be decided by you!)

The task needs to be done in FigJam. FigJam is a free to use and doesn't need to downloaded. It is very easy to learn and hardly takes 15 minutes to learn. If you are unclear on how to use it, check the tutorial here: [https://www.youtube.com/watch?v=RVNuArHH5WM](https://www.youtube.com/watch?v=RVNuArHH5WM) 

<br>

## Procedure:

1. Think about how the flow of the app will be for an average user who has just installed this app and is opening this app for the first time. The user is assumed to be unclear with the functionalities of the app.
2. You have decide how the user will move through the app, what steps will he need to take and in which order, for eg. the user first might need to sign up for the app, the fill some personal details, some personality traits etc. 
3. You can also add how and on what attributes the matching will take place. Mention any matching algorithm which you think is suitable.
4. Finally create your ideal user flow in a figjam file and provide its link (in .txt file). Submit your txt files in the USER EXPERIENCE TASK folder only.

If you are unclear with user flow diagrams check this short video here: [https://www.youtube.com/watch?v=cvYhuowazh0](https://www.youtube.com/watch?v=cvYhuowazh0) 

<br>

## MDC (Minimum Design Criteria)

The user flow can be very basic but at least needs to fulfil the basic functionality of the app that is the end result should be that each user finds his/her ideal roomie. The flow should begin from user entering the app for first time, till user finds his roommate.

For any doubts related to task or the submission process you can always ping us on discord ([https://discord.gg/4j5ub6TV](https://discord.gg/4j5ub6TV)). We will be happy to help.

**Comment by NEHA15012002** [comment]
Claim

**Comment by schandu-eng** [comment]
i want to claim this issue

**Comment by karrocks** [comment]
@schandu-eng This issue is open to all. You may start working.

**Comment by Abhijeet452** [comment]
Claim

**Comment by karrocks** [comment]
@Abhijeet452 This issue is OPEN TO ALL, you can start working on it without claiming it.

**Comment by codelord09** [comment]
claim

**Comment by karrocks** [comment]
@codelord09 This issue is OPEN TO ALL. You may start working :)

**Comment by juhiechandra** [comment]
I am sorry for the error as I did mistake in template. I hope you like my work.

**Comment by KIRTEE-TECH** [comment]
@karrocks I'm just done with the User Experience and User flow diagram in Figma can you please reopen this issue for some time so that i can submit my entry
