### ISSUE TITLE
It's a Redesign! Swipe Right...

### ISSUE THREAD

**Issue by karrocks** [opencodeiiita/Find-My-Roomie#303]
OPEN TO ALL

It's redesign time! Redesign the app which you had installed with the hopes of finding someone who would redesign your life💖. We all know how it went though😔

Anyways, swipe right to find your match ....ahem.... I mean **redesign the Tinder App**, all the 5 screens of the app. To avoid any confusion in our relationship😊, let me be clear, the 5 screens that need to be redesigned are : The main screen, Categories Screen, People who liked you screen, Messages screen and finally the profile screen. 

Since it is the beginning of a new phase of life✨... App actually, so you can change the colour theme, the layout or anything else that you want! Feel free to express your love here. Love of design💞, obviously!  

The redesign needs to be meaningful like relationships👫, should be logical and rational like an ideal partner😎, should look and feel minimal and beautiful like true love😌 and should obviously follow great UX and UI principles like a great designer🤣.

</br>

## Submission Guideline:

Along with your true feelings, attach in the PR the link to your figma file in .txt file and place it *with💓care* in the **Redesign Tinder** Folder only.

**Comment by Dheeraj096** [comment]
First time installing tinder 😂😂.
