### ISSUE TITLE
Quick UX task

### ISSUE THREAD

**Issue by karrocks** [opencodeiiita/Find-My-Roomie#4]
OPEN TO ALL

While you are working on the best user flow for Find My Roomie app, here is another short task to test your thinking as User Experience Designer!.
The task is short and requires very less time but what it requires more of is the keen eye to observe things from the perspective of the user

Everything in this world happens for a reason and same is the case with the WhatsApp home screen which looks a particular way based on various reasons for a better experience and ease of use for the users. 
Your task is to simply pen down your thoughts on why the WhatsApp home screen looks like the way it does, why the chats are arranged in the way they are and why is everything placed where they are placed😂. 

If you are confident enough you can even suggest changes in the layout or any other aspect of the homescreen which might lead to better user experience than it currently offers. Happy UXing contributors

**Remember to submit your response as .txt file in the Quick UX task folder only.** 

## Minimum Design Criteria (MDC)

Atleast suggest two features of the homescreen and how they contribute to good user experience and how would the experience have been worse if these features would have been implemented differently. You can also suggest two changes if that is what you prefer.

  

> Features doesn't have to mean very significant functions of the homescreen, they can be as simple as why the chats are sorted according to time and not by the number of unreads or anything which is similarly simple.
>

**Comment by anshrusia200** [comment]
Sir do have to just comment our responses here?

**Comment by deep-ika** [comment]
claim

**Comment by karrocks** [comment]
@deep-ika This issue is OPEN TO ALL, you may start working.
